{{- if .Values.resourceQuota.enabled -}}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.serviceName }}-quota
  namespace: {{ .Values.namespace }}
spec:
  hard:
    requests.cpu: {{ .Values.resourceQuota.hard.requests.cpu | quote }}
    requests.memory: {{ .Values.resourceQuota.hard.requests.memory | quote }}
    limits.cpu: {{ .Values.resourceQuota.hard.limits.cpu | quote }}
    limits.memory: {{ .Values.resourceQuota.hard.limits.memory | quote }}
    pods: {{ .Values.resourceQuota.hard.pods | quote }}
{{- end -}}
