apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: weather=sveshnikov/app
    argocd-image-updater.argoproj.io/weather.update-strategy: latest
    argocd-image-updater.argoproj.io/weather.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/weather.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: https://education-git.yadro.com/education/devops/2026/m.sveshnikov/app.git
    targetRevision: master
    path: ./weather-app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: weather-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
