apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://education-git.yadro.com/education/devops/2026/m.sveshnikov/app.git
    targetRevision: master
    path: ./weather-app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: weather-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
