apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: weather-updater
  namespace: argocd
spec:
  interval: 2m
  registries:
  - name: Docker Hub
    prefix: docker.io
    api_url: https://registry-1.docker.io
    credentials: pullsecret:argocd/dockerhub-secret
  applications:
  - name: weather-app
    kind: Application
    namespace: argocd
    images:
    - image: sveshnikov/app
      alias: weather
      updateStrategy: newest-build
      helm:
        imageName: image.repository
        imageTag: image.tag
