apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: weather-updater
  namespace: argocd
spec:
  commonUpdateSettings:
    pullSecret: "pullsecret:argocd/dockerhub-secret"
    updateStrategy: newest-build
  applicationRefs:
  - namePattern: "weather-app"
    images:
    - alias: weather
      imageName: sveshnikov/app
      manifestTargets:
        helm:
          name: image.repository
          tag: image.tag
  writeBackConfig:
    method: argocd
