---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: weather-app-secret
  namespace: weather-app
spec:
  encryptedData:
    API_KEY: AgDTSFbFpbASaGAtyPHnCZIXzGJ/dLqOz/6A13AUEAI1pEXzSVzuR9/5ZOveSkTzd5uHYH0u4rYA8KyK0SRTSANqv+hrhWPbOfHg8PcgMgDk6Fjq5rD60O10u0WkCIjCWbCKJaNzW6EnBoCntLvs+Hcox/Ak257mTs013KI39zDI2KF3ucZTJMOfdlgsKTzDEEYfO+fwEc2ztQhp+TcP7DLpktCILIy0PazjTN1SSiEEKECbnQAoY+cQm7mtdIp3rZqV3QFtM1D8Sy9p9lgPXb/1755cZvYA2uq4OxOFn9cvXpxAH4Thhv5pUUvLtjJKYtAqEyD07G7voJoltQcWD/tPNUgzPW/yOxdLcPt8dfXXBaQgQED1bs0TGfiL0taKu3gWy70SXWVMW6Yxwceo8Jx5vnCshKbitUuvHyL9OWX2ebVXeUa3y+c0wPDRMeP5fqIWDr32Vhcp12uIQbT4cogy5xRNq2Q75l8NMXE9xTBhAuuGXsCDzfHZ9F6bdyDTvi3+y6U3Ox1E5kWO+eO/TgtJ+qrarRtL8nSPM28sqj98kmFZ9mmt+EEYVp2bGOzlVaif7eFhx0pIr/F2+O3ilrRXeSMS+GHIdkhMbTSbBPpHpIZ9jdyH8VV2m1/tkBeYeEWJy8ENf6MjPOY00F1rPWEUrkzYm4JACqXRwIMopyTLX1c3zjqgTORXja8eXSWuMkm7cMFjaTVZLkkkTD+NtBDPBGelQ7mdnUo6
  template:
    metadata:
      name: weather-app-secret
      namespace: weather-app
    type: Opaque
