apiVersion: v1
kind: ResourceQuota
metadata:
  name: app-quota
  namespace: weather-app
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "2Gi"
    limits.cpu: "2"
    limits.memory: "4Gi"
    pods: "4"
